org: frontend2024thapa
service: swing-notes-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${file(./config.yml):aws.role}

build:
  esbuild:
    minify: true # Tells Serverless to bundle and minify code.
  package:
    individually: true # Package each Lambda separately

functions:
  GetNotes:
    handler: functions/GetNotes/index.handler
    events:
      - httpApi:
          path: /api/notes/{user}
          method: GET

  CreateNote:
    handler: functions/CreateNote/index.handler
    events:
      - httpApi:
          path: /api/notes/{user}
          method: POST

  UpdateNote:
    handler: functions/UpdateNote/index.handler
    events:
      - httpApi:
          path: /api/notes/{user}/{id}
          method: PUT

  DeleteNote:
    handler: functions/DeleteNote/index.handler
    events:
      - httpApi:
          path: /api/notes/{user}/{id}
          method: DELETE

resources:
  Resources:
    NotesDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "swing-notes-db"
        AttributeDefinitions:
          - AttributeName: "pk"
            AttributeType: "S"
          - AttributeName: "sk"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "pk"
            KeyType: "HASH"
          - AttributeName: "sk"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
